server:
  port: 8092

spring:
  application:
    name: client-manager
    
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      format_sql: false
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
